version: '3'

services:
  database:
    image: postgres:alpine

  elasticsearch:
    image: elasticsearch:7.17.9
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  redis:
    image: redis:alpine

volumes:
  db-data:
  elasticsearch-data:
