version: '3'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.local
    ports:
      - 80

  database:
    image: postgres:alpine

  elasticsearch:
    image: elasticsearch:7.17.9
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
      ES_JAVA_OPTS: "-Xmx256m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  redis:
    image: redis:alpine

volumes:
  db-data:
  elasticsearch-data:
