version: '3'

services:
  database:
    image: postgres:alpine

  elasticsearch:
    image: elasticsearch:7.17.9
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'

  redis:
    image: redis:alpine

  builder:
    build: ./
    volumes:
      - '.:/build'
