version: '3'

services:
  mailer:
    image: mailhog/mailhog:latest
    ports:
      - '8083:8025'

  database:
    ports:
      - '8084:3306'

  elasticsearch:
    ports:
      - '9200:9200'

  webserver:
    build:
      context: .
      dockerfile: docker/dev/nginx/Dockerfile
    working_dir: /application
    volumes:
      - '.:/application'
    ports:
      - '8080:80'
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/dev/php-fpm/Dockerfile
    working_dir: /application
    volumes:
      - '.:/application'
    depends_on:
      - database
      - elasticsearch
      - redis

  fe-builder:
    image: node:18-alpine
    working_dir: /build/assets/website
    command: sh -c "npm ci --no-audit --ignore-scripts && npm run watch"
    volumes:
      - '.:/build'

  be-builder:
    image: node:14-alpine
    working_dir: /build/assets/admin
    command: sh -c "npm install && npm run watch"
    volumes:
      - '.:/build'
