<?php

declare(strict_types=1);

namespace App\Tables\Columns;

use Filament\Tables\Columns\Column;

class ResourceNameColumn extends Column
{
    protected string $view = 'tables.columns.resource-name-column';

    public static function make(string $name): static
    {
        return parent::make($name); // TODO: Change the autogenerated stub
    }
}
