#!/command/with-contenv sh

cd /var/www

echo "
APP_SECRET=\"${APP_SECRET}\"
APP_ENV=\"${APP_ENV:-prod}\"

TRUSTED_PROXIES=\"${TRUSTED_PROXIES:-127.0.0.1}\"
TRUSTED_HOSTS=\"${TRUSTED_HOSTS:-localhost}\"

LOCK_DSN=\"${LOCK_DSN:-semaphore}\"

DATABASE_DRIVER=\"${DATABASE_DRIVER}\"
DATABASE_HOST=\"${DATABASE_HOST}\"
DATABASE_PORT=\"${DATABASE_PORT}\"
DATABASE_NAME=\"${DATABASE_NAME}\"
DATABASE_USERNAME=\"${DATABASE_USERNAME}\"
DATABASE_PASSWORD=\"${DATABASE_PASSWORD}\"
DATABASE_VERSION=\"${DATABASE_VERSION}\"

SULU_ADMIN_EMAIL=\"${SULU_ADMIN_EMAIL}\"

MEDIA_STORAGE=\"${MEDIA_STORAGE:-s3}\"
MEDIA_SAVE_IMAGE_LOCAL=\"${MEDIA_SAVE_IMAGE_LOCAL:-true}\"
S3_KEY=\"${S3_KEY}\"
S3_SECRET=\"${S3_SECRET}\"
S3_REGION=\"${S3_REGION}\"
S3_ENDPOINT=\"${S3_ENDPOINT}\"
S3_BUCKET_NAME=\"${S3_BUCKET_NAME}\"
S3_PATH_PREFIX=\"${S3_PATH_PREFIX}\"

REDIS_HOST=\"${REDIS_HOST}\"
REDIS_PASSWORD=\"${REDIS_PASSWORD}\"

PHPCR_BACKEND=\"${PHPCR_BACKEND:-doctrinedbal}\"
PHPCR_BACKEND_URL=\"${PHPCR_BACKEND_URL}\"
PHPCR_USER=\"${PHPCR_USER}\"
PHPCR_PASSWORD=\"${PHPCR_PASSWORD}\"
# JACKRABBIT_VERSION=\"${JACKRABBIT_VERSION}\"

ELASTICSEARCH_HOST=\"${ELASTICSEARCH_HOST}\"
ELASTICSEARCH_INDEX=\"${ELASTICSEARCH_INDEX:-su-articles}\"
ELASTICSEARCH_REPLICAS=\"${ELASTICSEARCH_REPLICAS:-0}\"
ELASTICSEARCH_SHARDS=\"${ELASTICSEARCH_SHARDS:-1}\"

MASSIVE_SEARCH_PREFIX=\"${MASSIVE_SEARCH_PREFIX:-massive}\"
" >.env

composer dump-env prod
composer auto-scripts
php bin/console sulu:build dev --destroy --no-interaction

chown -R www-data:www-data /var/www
